### ISSUE TITLE
Перевести контроллеры на использование Http Foundation

### ISSUE THREAD

**Issue by index0h** [pers1307/Blog#13]
см. https://github.com/symfony/http-foundation
http://symfony.com/doc/current/components/http_foundation/introduction.html

**Comment by index0h** [comment]
По сути задача следующая:
1. В экшнах контроллеров использовать только Request и в них же на выход давать Response.
2. Request формируется вне контроллера
3. Response выводится тоже вне контроллера

Использование $_GET, $_REQUEST, $_POST, $_FILES, $_COOKIE должно быть исключено. $_SESSION в сервисе авторизации пока что пусть останется.

**Comment by index0h** [comment]
По сути задача следующая:
1. В экшнах контроллеров использовать только Request и в них же на выход давать Response.
2. Request формируется вне контроллера
3. Response выводится тоже вне контроллера

Использование $_GET, $_REQUEST, $_POST, $_FILES, $_COOKIE должно быть исключено. $_SESSION в сервисе авторизации пока что пусть останется.

**Comment by pers1307** [comment]
Переведено на request
